spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwttoken
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
