version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jwttoken
#    volumes:
#      - mysql-jwl:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

#volumes:
#  mysql-jwl:
#    driver: local
