version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: jwt-tut
    volumes:
      - mysql-jwl:/var/lib/mysql
    ports:
      - "1000:1000"
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
    driver: local
