version: '3'
services:
  postgres-security:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
